services:
  backend:
    image: taskzen-backend-prod

    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - ./backend/.env.example

  frontend:
    image: taskzen-frontend-prod

    build:
      context: ./frontend
      dockerfile: Dockerfile

    depends_on:
      - backend