# Use lightweight Node Image
FROM node:22-alpine

# Set Working Directory
WORKDIR /app

# COPY Only Package file first
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the app
COPY . .

# Expose PORT
EXPOSE 8000

# Start app
CMD ["npm", "run", "dev"]