name: TaskZen CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =====================
      # Backend CI
      # =====================
      - name: Setup Node (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Backend Basic Check
        working-directory: backend
        run: node -v

      # =====================
      # Frontend CI
      # =====================
      - name: Setup Node (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Angular App
        working-directory: frontend
        run: npm run build -- --configuration production

      
      # =====================
      # Docker Build Check
      # =====================

      - name: Validate CI Compose
        run: docker compose -f docker-compose.ci.yml config

      # =====================
      # Docker Hub Login
      # =====================

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # =====================
      # Build & Push Backend
      # =====================

      - name: Build Backend Image
        run: |
          docker build -t iamprabhav/taskzen-backend:latest ./backend

      - name: Push Backend Image
        run: |
          docker push iamprabhav/taskzen-backend:latest

      # =====================
      # Build & Push Frontend
      # =====================

      - name: Build Frontend Image
        run: |
          docker build -t iamprabhav/taskzen-frontend:latest ./frontend

      - name: Push Frontend Image
        run: |
          docker push iamprabhav/taskzen-frontend:latest